import BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean.BernoulliEulerObjects
import BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean.BernoulliEulerAdmissibleClass
import BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean.BernoulliEulerBridgeLemmas
import BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean.BernoulliEulerGateLemmas
import BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean.BernoulliEulerFinalTheorem
import BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean.BernoulliEulerCertificate

namespace HautevilleHouse
namespace BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean

-- This module is the root of the BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean Lean proof package.

def sourceRepository : String := "BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean"
def sourceDescription : String := "Bernoulli and Euler Numbers and Polynomials Foundation"

end BernoulliEulerNumbersPolynomialsFoundationCanonicalLaneLean
end HautevilleHouse